export default [
  'ATV',
  'Mulcher',
  'Pickup',
  'Rock Truck',
  'Saw Crew',
  'Water Truck',
  'Vac Truck',
  'Plow',
  'Excavator',
  'Grater',
]

export const colorMap = {
  ATV: '#8dd3c7',
  Mulcher: '#ffffb3',
  Pickup: '#bebada',
  'Rock Truck': '#fb8072',
  'Saw Crew': '#80b1d3',
  'Water Truck': '#fdb462',
  'Vac Truck': '#b3de69',
  Plow: '#fccde5',
  Excavator: '#bc80bd',
  Grater: '#ccebc5',
}

export const mapboxColourExpression = [
  'case',
  ['==', ['get', 'vehicleType'], 'ATV'],
  '#8dd3c7',
  ['==', ['get', 'vehicleType'], 'Mulcher'],
  '#ffffb3',
  ['==', ['get', 'vehicleType'], 'Pickup'],
  '#bebada',
  ['==', ['get', 'vehicleType'], 'Rock Truck'],
  '#fb8072',
  ['==', ['get', 'vehicleType'], 'Saw Crew'],
  '#80b1d3',
  ['==', ['get', 'vehicleType'], 'Water Truck'],
  '#fdb462',
  ['==', ['get', 'vehicleType'], 'Vac Truck'],
  '#b3de69',
  ['==', ['get', 'vehicleType'], 'Plow'],
  '#fccde5',
  ['==', ['get', 'vehicleType'], 'Excavator'],
  '#bc80bd',
  ['==', ['get', 'vehicleType'], 'Grater'],
  '#ccebc5',
  // One should never get red. Red bad.
  '#ff0000',
]
